export const ABI = [
	{
		inputs: [{ internalType: 'address', name: 'ORDER_MANAGER_SINGLETON_', type: 'address' }],
		stateMutability: 'nonpayable',
		type: 'constructor',
	},
	{ inputs: [], name: 'AboveMaxTimelock', type: 'error' },
	{ inputs: [], name: 'AlreadyPending', type: 'error' },
	{ inputs: [], name: 'AlreadySet', type: 'error' },
	{ inputs: [], name: 'BelowMinTimelock', type: 'error' },
	{ inputs: [], name: 'CanNotTransferUintMax', type: 'error' },
	{ inputs: [], name: 'CollateralIsAsset', type: 'error' },
	{
		inputs: [
			{ internalType: 'address', name: 'spender', type: 'address' },
			{ internalType: 'uint256', name: 'allowance', type: 'uint256' },
			{ internalType: 'uint256', name: 'needed', type: 'uint256' },
		],
		name: 'ERC20InsufficientAllowance',
		type: 'error',
	},
	{
		inputs: [
			{ internalType: 'address', name: 'sender', type: 'address' },
			{ internalType: 'uint256', name: 'balance', type: 'uint256' },
			{ internalType: 'uint256', name: 'needed', type: 'uint256' },
		],
		name: 'ERC20InsufficientBalance',
		type: 'error',
	},
	{ inputs: [{ internalType: 'address', name: 'approver', type: 'address' }], name: 'ERC20InvalidApprover', type: 'error' },
	{ inputs: [{ internalType: 'address', name: 'receiver', type: 'address' }], name: 'ERC20InvalidReceiver', type: 'error' },
	{ inputs: [{ internalType: 'address', name: 'sender', type: 'address' }], name: 'ERC20InvalidSender', type: 'error' },
	{ inputs: [{ internalType: 'address', name: 'spender', type: 'address' }], name: 'ERC20InvalidSpender', type: 'error' },
	{
		inputs: [
			{ internalType: 'address', name: 'receiver', type: 'address' },
			{ internalType: 'uint256', name: 'assets', type: 'uint256' },
			{ internalType: 'uint256', name: 'max', type: 'uint256' },
		],
		name: 'ERC4626ExceededMaxDeposit',
		type: 'error',
	},
	{
		inputs: [
			{ internalType: 'address', name: 'receiver', type: 'address' },
			{ internalType: 'uint256', name: 'shares', type: 'uint256' },
			{ internalType: 'uint256', name: 'max', type: 'uint256' },
		],
		name: 'ERC4626ExceededMaxMint',
		type: 'error',
	},
	{
		inputs: [
			{ internalType: 'address', name: 'owner', type: 'address' },
			{ internalType: 'uint256', name: 'shares', type: 'uint256' },
			{ internalType: 'uint256', name: 'max', type: 'uint256' },
		],
		name: 'ERC4626ExceededMaxRedeem',
		type: 'error',
	},
	{
		inputs: [
			{ internalType: 'address', name: 'owner', type: 'address' },
			{ internalType: 'uint256', name: 'assets', type: 'uint256' },
			{ internalType: 'uint256', name: 'max', type: 'uint256' },
		],
		name: 'ERC4626ExceededMaxWithdraw',
		type: 'error',
	},
	{ inputs: [], name: 'EnforcedPause', type: 'error' },
	{ inputs: [], name: 'ExpectedPause', type: 'error' },
	{ inputs: [], name: 'InvalidActionId', type: 'error' },
	{ inputs: [], name: 'InvalidInitialization', type: 'error' },
	{ inputs: [], name: 'NoPendingValue', type: 'error' },
	{ inputs: [], name: 'NotCuratorRole', type: 'error' },
	{ inputs: [], name: 'NotGuardianRole', type: 'error' },
	{ inputs: [], name: 'NotInitializing', type: 'error' },
	{ inputs: [{ internalType: 'address', name: 'owner', type: 'address' }], name: 'OwnableInvalidOwner', type: 'error' },
	{ inputs: [{ internalType: 'address', name: 'account', type: 'address' }], name: 'OwnableUnauthorizedAccount', type: 'error' },
	{ inputs: [], name: 'PerformanceFeeRateExceeded', type: 'error' },
	{ inputs: [], name: 'ReentrancyGuardReentrantCall', type: 'error' },
	{ inputs: [], name: 'ReentrantCall', type: 'error' },
	{
		inputs: [
			{ internalType: 'uint256', name: 'actionId', type: 'uint256' },
			{ internalType: 'uint256', name: 'oldActionId', type: 'uint256' },
		],
		name: 'ReentrantCallBetweenActions',
		type: 'error',
	},
	{
		inputs: [
			{ internalType: 'uint8', name: 'bits', type: 'uint8' },
			{ internalType: 'uint256', name: 'value', type: 'uint256' },
		],
		name: 'SafeCastOverflowedUintDowncast',
		type: 'error',
	},
	{ inputs: [{ internalType: 'address', name: 'token', type: 'address' }], name: 'SafeERC20FailedOperation', type: 'error' },
	{ inputs: [], name: 'SupplyQueueNoLongerSupported', type: 'error' },
	{ inputs: [], name: 'TimelockNotElapsed', type: 'error' },
	{ inputs: [], name: 'UseApyInsteadOfApr', type: 'error' },
	{ inputs: [], name: 'UseVaultInitialParamsV2', type: 'error' },
	{ inputs: [], name: 'WithdrawalQueueNoLongerSupported', type: 'error' },
	{
		anonymous: false,
		inputs: [
			{ indexed: true, internalType: 'address', name: 'owner', type: 'address' },
			{ indexed: true, internalType: 'address', name: 'spender', type: 'address' },
			{ indexed: false, internalType: 'uint256', name: 'value', type: 'uint256' },
		],
		name: 'Approval',
		type: 'event',
	},
	{
		anonymous: false,
		inputs: [
			{ indexed: true, internalType: 'address', name: 'caller', type: 'address' },
			{ indexed: true, internalType: 'address', name: 'recipient', type: 'address' },
			{ indexed: true, internalType: 'address', name: 'collateral', type: 'address' },
			{ indexed: false, internalType: 'uint256', name: 'badDebt', type: 'uint256' },
			{ indexed: false, internalType: 'uint256', name: 'shares', type: 'uint256' },
			{ indexed: false, internalType: 'uint256', name: 'collateralOut', type: 'uint256' },
		],
		name: 'DealBadDebt',
		type: 'event',
	},
	{
		anonymous: false,
		inputs: [
			{ indexed: true, internalType: 'address', name: 'sender', type: 'address' },
			{ indexed: true, internalType: 'address', name: 'owner', type: 'address' },
			{ indexed: false, internalType: 'uint256', name: 'assets', type: 'uint256' },
			{ indexed: false, internalType: 'uint256', name: 'shares', type: 'uint256' },
		],
		name: 'Deposit',
		type: 'event',
	},
	{
		anonymous: false,
		inputs: [{ indexed: false, internalType: 'uint64', name: 'version', type: 'uint64' }],
		name: 'Initialized',
		type: 'event',
	},
	{
		anonymous: false,
		inputs: [
			{ indexed: true, internalType: 'address', name: 'previousOwner', type: 'address' },
			{ indexed: true, internalType: 'address', name: 'newOwner', type: 'address' },
		],
		name: 'OwnershipTransferStarted',
		type: 'event',
	},
	{
		anonymous: false,
		inputs: [
			{ indexed: true, internalType: 'address', name: 'previousOwner', type: 'address' },
			{ indexed: true, internalType: 'address', name: 'newOwner', type: 'address' },
		],
		name: 'OwnershipTransferred',
		type: 'event',
	},
	{
		anonymous: false,
		inputs: [{ indexed: false, internalType: 'address', name: 'account', type: 'address' }],
		name: 'Paused',
		type: 'event',
	},
	{
		anonymous: false,
		inputs: [{ indexed: true, internalType: 'address', name: 'caller', type: 'address' }],
		name: 'RevokePendingGuardian',
		type: 'event',
	},
	{
		anonymous: false,
		inputs: [
			{ indexed: true, internalType: 'address', name: 'caller', type: 'address' },
			{ indexed: true, internalType: 'address', name: 'market', type: 'address' },
		],
		name: 'RevokePendingMarket',
		type: 'event',
	},
	{
		anonymous: false,
		inputs: [{ indexed: true, internalType: 'address', name: 'caller', type: 'address' }],
		name: 'RevokePendingMinApy',
		type: 'event',
	},
	{
		anonymous: false,
		inputs: [{ indexed: true, internalType: 'address', name: 'caller', type: 'address' }],
		name: 'RevokePendingPerformanceFeeRate',
		type: 'event',
	},
	{
		anonymous: false,
		inputs: [{ indexed: true, internalType: 'address', name: 'caller', type: 'address' }],
		name: 'RevokePendingPool',
		type: 'event',
	},
	{
		anonymous: false,
		inputs: [{ indexed: true, internalType: 'address', name: 'caller', type: 'address' }],
		name: 'RevokePendingTimelock',
		type: 'event',
	},
	{
		anonymous: false,
		inputs: [
			{ indexed: true, internalType: 'address', name: 'caller', type: 'address' },
			{ indexed: false, internalType: 'uint256', name: 'newCapacity', type: 'uint256' },
		],
		name: 'SetCapacity',
		type: 'event',
	},
	{
		anonymous: false,
		inputs: [{ indexed: false, internalType: 'address', name: 'newCurator', type: 'address' }],
		name: 'SetCurator',
		type: 'event',
	},
	{
		anonymous: false,
		inputs: [
			{ indexed: true, internalType: 'address', name: 'caller', type: 'address' },
			{ indexed: false, internalType: 'address', name: 'newGuardian', type: 'address' },
		],
		name: 'SetGuardian',
		type: 'event',
	},
	{
		anonymous: false,
		inputs: [
			{ indexed: true, internalType: 'address', name: 'caller', type: 'address' },
			{ indexed: true, internalType: 'address', name: 'market', type: 'address' },
			{ indexed: false, internalType: 'bool', name: 'isWhitelisted', type: 'bool' },
		],
		name: 'SetMarketWhitelist',
		type: 'event',
	},
	{
		anonymous: false,
		inputs: [
			{ indexed: true, internalType: 'address', name: 'caller', type: 'address' },
			{ indexed: false, internalType: 'uint64', name: 'newMinApy', type: 'uint64' },
		],
		name: 'SetMinApy',
		type: 'event',
	},
	{
		anonymous: false,
		inputs: [
			{ indexed: true, internalType: 'address', name: 'caller', type: 'address' },
			{ indexed: false, internalType: 'uint256', name: 'newPerformanceFeeRate', type: 'uint256' },
		],
		name: 'SetPerformanceFeeRate',
		type: 'event',
	},
	{
		anonymous: false,
		inputs: [
			{ indexed: true, internalType: 'address', name: 'caller', type: 'address' },
			{ indexed: true, internalType: 'address', name: 'pool', type: 'address' },
		],
		name: 'SetPool',
		type: 'event',
	},
	{
		anonymous: false,
		inputs: [
			{ indexed: true, internalType: 'address', name: 'caller', type: 'address' },
			{ indexed: false, internalType: 'uint256', name: 'newTimelock', type: 'uint256' },
		],
		name: 'SetTimelock',
		type: 'event',
	},
	{
		anonymous: false,
		inputs: [
			{ indexed: false, internalType: 'address', name: 'newGuardian', type: 'address' },
			{ indexed: false, internalType: 'uint64', name: 'validAt', type: 'uint64' },
		],
		name: 'SubmitGuardian',
		type: 'event',
	},
	{
		anonymous: false,
		inputs: [
			{ indexed: true, internalType: 'address', name: 'market', type: 'address' },
			{ indexed: false, internalType: 'uint64', name: 'validAt', type: 'uint64' },
		],
		name: 'SubmitMarketToWhitelist',
		type: 'event',
	},
	{
		anonymous: false,
		inputs: [
			{ indexed: false, internalType: 'uint64', name: 'newMinApy', type: 'uint64' },
			{ indexed: false, internalType: 'uint64', name: 'validAt', type: 'uint64' },
		],
		name: 'SubmitMinApy',
		type: 'event',
	},
	{
		anonymous: false,
		inputs: [
			{ indexed: true, internalType: 'address', name: 'pool', type: 'address' },
			{ indexed: false, internalType: 'uint64', name: 'validAt', type: 'uint64' },
		],
		name: 'SubmitPendingPool',
		type: 'event',
	},
	{
		anonymous: false,
		inputs: [
			{ indexed: false, internalType: 'uint256', name: 'newPerformanceFeeRate', type: 'uint256' },
			{ indexed: false, internalType: 'uint64', name: 'validAt', type: 'uint64' },
		],
		name: 'SubmitPerformanceFeeRate',
		type: 'event',
	},
	{
		anonymous: false,
		inputs: [
			{ indexed: false, internalType: 'uint256', name: 'newTimelock', type: 'uint256' },
			{ indexed: false, internalType: 'uint64', name: 'validAt', type: 'uint64' },
		],
		name: 'SubmitTimelock',
		type: 'event',
	},
	{
		anonymous: false,
		inputs: [
			{ indexed: true, internalType: 'address', name: 'from', type: 'address' },
			{ indexed: true, internalType: 'address', name: 'to', type: 'address' },
			{ indexed: false, internalType: 'uint256', name: 'value', type: 'uint256' },
		],
		name: 'Transfer',
		type: 'event',
	},
	{
		anonymous: false,
		inputs: [{ indexed: false, internalType: 'address', name: 'account', type: 'address' }],
		name: 'Unpaused',
		type: 'event',
	},
	{
		anonymous: false,
		inputs: [
			{ indexed: true, internalType: 'address', name: 'sender', type: 'address' },
			{ indexed: true, internalType: 'address', name: 'receiver', type: 'address' },
			{ indexed: true, internalType: 'address', name: 'owner', type: 'address' },
			{ indexed: false, internalType: 'uint256', name: 'assets', type: 'uint256' },
			{ indexed: false, internalType: 'uint256', name: 'shares', type: 'uint256' },
		],
		name: 'Withdraw',
		type: 'event',
	},
	{
		anonymous: false,
		inputs: [
			{ indexed: true, internalType: 'address', name: 'caller', type: 'address' },
			{ indexed: true, internalType: 'address', name: 'recipient', type: 'address' },
			{ indexed: true, internalType: 'address', name: 'order', type: 'address' },
			{ indexed: false, internalType: 'uint256', name: 'amount', type: 'uint256' },
			{ indexed: false, internalType: 'uint256', name: 'shares', type: 'uint256' },
		],
		name: 'WithdrawFts',
		type: 'event',
	},
	{
		inputs: [],
		name: 'ORDER_MANAGER_SINGLETON',
		outputs: [{ internalType: 'address', name: '', type: 'address' }],
		stateMutability: 'view',
		type: 'function',
	},
	{ inputs: [], name: 'acceptGuardian', outputs: [], stateMutability: 'nonpayable', type: 'function' },
	{
		inputs: [{ internalType: 'address', name: 'market', type: 'address' }],
		name: 'acceptMarket',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{ inputs: [], name: 'acceptOwnership', outputs: [], stateMutability: 'nonpayable', type: 'function' },
	{ inputs: [], name: 'acceptPendingMinApy', outputs: [], stateMutability: 'nonpayable', type: 'function' },
	{ inputs: [], name: 'acceptPerformanceFeeRate', outputs: [], stateMutability: 'nonpayable', type: 'function' },
	{ inputs: [], name: 'acceptPool', outputs: [], stateMutability: 'nonpayable', type: 'function' },
	{ inputs: [], name: 'acceptTimelock', outputs: [], stateMutability: 'nonpayable', type: 'function' },
	{
		inputs: [],
		name: 'accretingPrincipal',
		outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [
			{ internalType: 'uint256', name: 'ftReserve', type: 'uint256' },
			{ internalType: 'uint256', name: 'xtReserve', type: 'uint256' },
			{ internalType: 'int256', name: 'deltaFt', type: 'int256' },
			{ internalType: 'int256', name: 'deltaXt', type: 'int256' },
		],
		name: 'afterSwap',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [
			{ internalType: 'address', name: 'owner', type: 'address' },
			{ internalType: 'address', name: 'spender', type: 'address' },
		],
		name: 'allowance',
		outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [],
		name: 'annualizedInterest',
		outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [
			{ internalType: 'address', name: 'spender', type: 'address' },
			{ internalType: 'uint256', name: 'value', type: 'uint256' },
		],
		name: 'approve',
		outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [],
		name: 'apr',
		outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [],
		name: 'apy',
		outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [],
		name: 'asset',
		outputs: [{ internalType: 'address', name: '', type: 'address' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [{ internalType: 'address', name: 'collateral', type: 'address' }],
		name: 'badDebtMapping',
		outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [{ internalType: 'address', name: 'account', type: 'address' }],
		name: 'balanceOf',
		outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [{ internalType: 'uint256', name: 'shares', type: 'uint256' }],
		name: 'convertToAssets',
		outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [{ internalType: 'uint256', name: 'assets', type: 'uint256' }],
		name: 'convertToShares',
		outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [
			{ internalType: 'contract ITermMaxMarketV2', name: 'market', type: 'address' },
			{
				components: [
					{ internalType: 'uint256', name: 'originalVirtualXtReserve', type: 'uint256' },
					{ internalType: 'uint256', name: 'virtualXtReserve', type: 'uint256' },
					{ internalType: 'uint256', name: 'maxXtReserve', type: 'uint256' },
					{
						components: [
							{
								components: [
									{ internalType: 'uint256', name: 'xtReserve', type: 'uint256' },
									{ internalType: 'uint256', name: 'liqSquare', type: 'uint256' },
									{ internalType: 'int256', name: 'offset', type: 'int256' },
								],
								internalType: 'struct CurveCut[]',
								name: 'lendCurveCuts',
								type: 'tuple[]',
							},
							{
								components: [
									{ internalType: 'uint256', name: 'xtReserve', type: 'uint256' },
									{ internalType: 'uint256', name: 'liqSquare', type: 'uint256' },
									{ internalType: 'int256', name: 'offset', type: 'int256' },
								],
								internalType: 'struct CurveCut[]',
								name: 'borrowCurveCuts',
								type: 'tuple[]',
							},
						],
						internalType: 'struct CurveCuts',
						name: 'curveCuts',
						type: 'tuple',
					},
				],
				internalType: 'struct OrderV2ConfigurationParams',
				name: 'params',
				type: 'tuple',
			},
		],
		name: 'createOrder',
		outputs: [{ internalType: 'contract ITermMaxOrderV2', name: 'order', type: 'address' }],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [],
		name: 'curator',
		outputs: [{ internalType: 'address', name: '', type: 'address' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [
			{ internalType: 'address', name: 'collateral', type: 'address' },
			{ internalType: 'uint256', name: 'badDebtAmt', type: 'uint256' },
			{ internalType: 'address', name: 'recipient', type: 'address' },
			{ internalType: 'address', name: 'owner', type: 'address' },
		],
		name: 'dealBadDebt',
		outputs: [
			{ internalType: 'uint256', name: 'shares', type: 'uint256' },
			{ internalType: 'uint256', name: 'collateralOut', type: 'uint256' },
		],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [],
		name: 'decimals',
		outputs: [{ internalType: 'uint8', name: '', type: 'uint8' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [
			{ internalType: 'uint256', name: 'assets', type: 'uint256' },
			{ internalType: 'address', name: 'receiver', type: 'address' },
		],
		name: 'deposit',
		outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [],
		name: 'getVersion',
		outputs: [{ internalType: 'string', name: '', type: 'string' }],
		stateMutability: 'pure',
		type: 'function',
	},
	{
		inputs: [],
		name: 'guardian',
		outputs: [{ internalType: 'address', name: '', type: 'address' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [
			{
				components: [
					{ internalType: 'address', name: 'admin', type: 'address' },
					{ internalType: 'address', name: 'curator', type: 'address' },
					{ internalType: 'uint256', name: 'timelock', type: 'uint256' },
					{ internalType: 'contract IERC20', name: 'asset', type: 'address' },
					{ internalType: 'uint256', name: 'maxCapacity', type: 'uint256' },
					{ internalType: 'string', name: 'name', type: 'string' },
					{ internalType: 'string', name: 'symbol', type: 'string' },
					{ internalType: 'uint64', name: 'performanceFeeRate', type: 'uint64' },
				],
				internalType: 'struct VaultInitialParams',
				name: '',
				type: 'tuple',
			},
		],
		name: 'initialize',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [
			{
				components: [
					{ internalType: 'address', name: 'admin', type: 'address' },
					{ internalType: 'address', name: 'curator', type: 'address' },
					{ internalType: 'address', name: 'guardian', type: 'address' },
					{ internalType: 'uint256', name: 'timelock', type: 'uint256' },
					{ internalType: 'contract IERC20', name: 'asset', type: 'address' },
					{ internalType: 'contract IERC4626', name: 'pool', type: 'address' },
					{ internalType: 'uint256', name: 'maxCapacity', type: 'uint256' },
					{ internalType: 'string', name: 'name', type: 'string' },
					{ internalType: 'string', name: 'symbol', type: 'string' },
					{ internalType: 'uint64', name: 'performanceFeeRate', type: 'uint64' },
					{ internalType: 'uint64', name: 'minApy', type: 'uint64' },
				],
				internalType: 'struct VaultInitialParamsV2',
				name: 'params',
				type: 'tuple',
			},
		],
		name: 'initialize',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [{ internalType: 'address', name: 'market', type: 'address' }],
		name: 'marketWhitelist',
		outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [{ internalType: 'address', name: '', type: 'address' }],
		name: 'maxDeposit',
		outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [{ internalType: 'address', name: '', type: 'address' }],
		name: 'maxMint',
		outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [{ internalType: 'address', name: 'owner', type: 'address' }],
		name: 'maxRedeem',
		outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [{ internalType: 'address', name: 'owner', type: 'address' }],
		name: 'maxWithdraw',
		outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [],
		name: 'minApy',
		outputs: [{ internalType: 'uint64', name: '', type: 'uint64' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [
			{ internalType: 'uint256', name: 'shares', type: 'uint256' },
			{ internalType: 'address', name: 'receiver', type: 'address' },
		],
		name: 'mint',
		outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [],
		name: 'name',
		outputs: [{ internalType: 'string', name: '', type: 'string' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [{ internalType: 'address', name: 'order', type: 'address' }],
		name: 'orderMaturity',
		outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [],
		name: 'owner',
		outputs: [{ internalType: 'address', name: '', type: 'address' }],
		stateMutability: 'view',
		type: 'function',
	},
	{ inputs: [], name: 'pause', outputs: [], stateMutability: 'nonpayable', type: 'function' },
	{ inputs: [], name: 'paused', outputs: [{ internalType: 'bool', name: '', type: 'bool' }], stateMutability: 'view', type: 'function' },
	{
		inputs: [],
		name: 'pendingGuardian',
		outputs: [
			{
				components: [
					{ internalType: 'address', name: 'value', type: 'address' },
					{ internalType: 'uint64', name: 'validAt', type: 'uint64' },
				],
				internalType: 'struct PendingAddress',
				name: '',
				type: 'tuple',
			},
		],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [{ internalType: 'address', name: 'market', type: 'address' }],
		name: 'pendingMarkets',
		outputs: [
			{
				components: [
					{ internalType: 'uint192', name: 'value', type: 'uint192' },
					{ internalType: 'uint64', name: 'validAt', type: 'uint64' },
				],
				internalType: 'struct PendingUint192',
				name: '',
				type: 'tuple',
			},
		],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [],
		name: 'pendingMinApy',
		outputs: [
			{
				components: [
					{ internalType: 'uint192', name: 'value', type: 'uint192' },
					{ internalType: 'uint64', name: 'validAt', type: 'uint64' },
				],
				internalType: 'struct PendingUint192',
				name: '',
				type: 'tuple',
			},
		],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [],
		name: 'pendingOwner',
		outputs: [{ internalType: 'address', name: '', type: 'address' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [],
		name: 'pendingPerformanceFeeRate',
		outputs: [
			{
				components: [
					{ internalType: 'uint192', name: 'value', type: 'uint192' },
					{ internalType: 'uint64', name: 'validAt', type: 'uint64' },
				],
				internalType: 'struct PendingUint192',
				name: '',
				type: 'tuple',
			},
		],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [],
		name: 'pendingPool',
		outputs: [
			{
				components: [
					{ internalType: 'address', name: 'value', type: 'address' },
					{ internalType: 'uint64', name: 'validAt', type: 'uint64' },
				],
				internalType: 'struct PendingAddress',
				name: '',
				type: 'tuple',
			},
		],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [],
		name: 'pendingPools',
		outputs: [
			{
				components: [
					{ internalType: 'address', name: 'value', type: 'address' },
					{ internalType: 'uint64', name: 'validAt', type: 'uint64' },
				],
				internalType: 'struct PendingAddress',
				name: '',
				type: 'tuple',
			},
		],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [],
		name: 'pendingTimelock',
		outputs: [
			{
				components: [
					{ internalType: 'uint192', name: 'value', type: 'uint192' },
					{ internalType: 'uint64', name: 'validAt', type: 'uint64' },
				],
				internalType: 'struct PendingUint192',
				name: '',
				type: 'tuple',
			},
		],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [],
		name: 'performanceFee',
		outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [],
		name: 'performanceFeeRate',
		outputs: [{ internalType: 'uint64', name: '', type: 'uint64' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [],
		name: 'pool',
		outputs: [{ internalType: 'contract IERC4626', name: '', type: 'address' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [{ internalType: 'uint256', name: 'assets', type: 'uint256' }],
		name: 'previewDeposit',
		outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [{ internalType: 'uint256', name: 'shares', type: 'uint256' }],
		name: 'previewMint',
		outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [{ internalType: 'uint256', name: 'shares', type: 'uint256' }],
		name: 'previewRedeem',
		outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [{ internalType: 'uint256', name: 'assets', type: 'uint256' }],
		name: 'previewWithdraw',
		outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [
			{ internalType: 'uint256', name: 'shares', type: 'uint256' },
			{ internalType: 'address', name: 'receiver', type: 'address' },
			{ internalType: 'address', name: 'owner', type: 'address' },
		],
		name: 'redeem',
		outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [{ internalType: 'contract ITermMaxOrderV2', name: 'order', type: 'address' }],
		name: 'redeemOrder',
		outputs: [
			{ internalType: 'uint256', name: 'badDebt', type: 'uint256' },
			{ internalType: 'uint256', name: 'deliveryCollateral', type: 'uint256' },
		],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [
			{ internalType: 'address[]', name: 'orders', type: 'address[]' },
			{ internalType: 'uint256[]', name: 'removedLiquidities', type: 'uint256[]' },
		],
		name: 'removeLiquidityFromOrders',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{ inputs: [], name: 'renounceOwnership', outputs: [], stateMutability: 'nonpayable', type: 'function' },
	{ inputs: [], name: 'revokePendingGuardian', outputs: [], stateMutability: 'nonpayable', type: 'function' },
	{
		inputs: [{ internalType: 'address', name: 'market', type: 'address' }],
		name: 'revokePendingMarket',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{ inputs: [], name: 'revokePendingMinApy', outputs: [], stateMutability: 'nonpayable', type: 'function' },
	{ inputs: [], name: 'revokePendingPerformanceFeeRate', outputs: [], stateMutability: 'nonpayable', type: 'function' },
	{ inputs: [], name: 'revokePendingPool', outputs: [], stateMutability: 'nonpayable', type: 'function' },
	{ inputs: [], name: 'revokePendingTimelock', outputs: [], stateMutability: 'nonpayable', type: 'function' },
	{
		inputs: [{ internalType: 'uint256', name: 'newCapacity', type: 'uint256' }],
		name: 'setCapacity',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [{ internalType: 'address', name: 'newCurator', type: 'address' }],
		name: 'setCurator',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [{ internalType: 'address', name: 'newGuardian', type: 'address' }],
		name: 'submitGuardian',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [
			{ internalType: 'address', name: 'market', type: 'address' },
			{ internalType: 'bool', name: 'isWhitelisted', type: 'bool' },
		],
		name: 'submitMarket',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [{ internalType: 'uint64', name: 'newMinApy', type: 'uint64' }],
		name: 'submitPendingMinApy',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [{ internalType: 'address', name: 'pool_', type: 'address' }],
		name: 'submitPendingPool',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [{ internalType: 'uint184', name: 'newPerformanceFeeRate', type: 'uint184' }],
		name: 'submitPerformanceFeeRate',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [{ internalType: 'uint256', name: 'newTimelock', type: 'uint256' }],
		name: 'submitTimelock',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
		name: 'supplyQueue',
		outputs: [{ internalType: 'address', name: '', type: 'address' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [],
		name: 'supplyQueueLength',
		outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [],
		name: 'symbol',
		outputs: [{ internalType: 'string', name: '', type: 'string' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [],
		name: 'timelock',
		outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [],
		name: 'totalAssets',
		outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [],
		name: 'totalFt',
		outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [],
		name: 'totalSupply',
		outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [
			{ internalType: 'address', name: 'to', type: 'address' },
			{ internalType: 'uint256', name: 'value', type: 'uint256' },
		],
		name: 'transfer',
		outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [
			{ internalType: 'address', name: 'from', type: 'address' },
			{ internalType: 'address', name: 'to', type: 'address' },
			{ internalType: 'uint256', name: 'value', type: 'uint256' },
		],
		name: 'transferFrom',
		outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [{ internalType: 'address', name: 'newOwner', type: 'address' }],
		name: 'transferOwnership',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{ inputs: [], name: 'unpause', outputs: [], stateMutability: 'nonpayable', type: 'function' },
	{
		inputs: [
			{ internalType: 'address[]', name: 'orders', type: 'address[]' },
			{
				components: [
					{ internalType: 'uint256', name: 'originalVirtualXtReserve', type: 'uint256' },
					{ internalType: 'uint256', name: 'virtualXtReserve', type: 'uint256' },
					{ internalType: 'uint256', name: 'maxXtReserve', type: 'uint256' },
					{
						components: [
							{
								components: [
									{ internalType: 'uint256', name: 'xtReserve', type: 'uint256' },
									{ internalType: 'uint256', name: 'liqSquare', type: 'uint256' },
									{ internalType: 'int256', name: 'offset', type: 'int256' },
								],
								internalType: 'struct CurveCut[]',
								name: 'lendCurveCuts',
								type: 'tuple[]',
							},
							{
								components: [
									{ internalType: 'uint256', name: 'xtReserve', type: 'uint256' },
									{ internalType: 'uint256', name: 'liqSquare', type: 'uint256' },
									{ internalType: 'int256', name: 'offset', type: 'int256' },
								],
								internalType: 'struct CurveCut[]',
								name: 'borrowCurveCuts',
								type: 'tuple[]',
							},
						],
						internalType: 'struct CurveCuts',
						name: 'curveCuts',
						type: 'tuple',
					},
				],
				internalType: 'struct OrderV2ConfigurationParams[]',
				name: 'orderConfigs',
				type: 'tuple[]',
			},
		],
		name: 'updateOrdersConfiguration',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [
			{ internalType: 'uint256', name: 'assets', type: 'uint256' },
			{ internalType: 'address', name: 'receiver', type: 'address' },
			{ internalType: 'address', name: 'owner', type: 'address' },
		],
		name: 'withdraw',
		outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [
			{ internalType: 'address', name: 'order', type: 'address' },
			{ internalType: 'uint256', name: 'amount', type: 'uint256' },
			{ internalType: 'address', name: 'recipient', type: 'address' },
			{ internalType: 'address', name: 'owner', type: 'address' },
		],
		name: 'withdrawFts',
		outputs: [{ internalType: 'uint256', name: 'shares', type: 'uint256' }],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [
			{ internalType: 'address', name: 'recipient', type: 'address' },
			{ internalType: 'uint256', name: 'amount', type: 'uint256' },
		],
		name: 'withdrawPerformanceFee',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
		name: 'withdrawQueue',
		outputs: [{ internalType: 'address', name: '', type: 'address' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [],
		name: 'withdrawQueueLength',
		outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
		stateMutability: 'view',
		type: 'function',
	},
] as const;
